# Generated by Django 4.2.4 on 2023-08-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scrapeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField()),
                ('Name_Of_Img', models.CharField(max_length=200)),
                ('Date_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
